### ISSUE TITLE
GUI Broken Catalina?

### ISSUE THREAD

**Issue by ipwnosx** [LocalXpose/node-localxpose#1]
GUI WONT SHOW INTERFACE IN Catalina, cli runs fine 

![Screen Shot 2020-07-02 at 6 39 25 PM](https://user-images.githubusercontent.com/41032246/86420797-ed431680-bc94-11ea-90b7-c993db011e30.png)

**Comment by LocalXpose** [comment]
This is not related to the current repository, please send this bug to hello@localxpose.io.
